apiVersion: v1
kind: Service
metadata:
  labels:
    app: uptimekuma
  name: uptimekuma
spec:
  type: NodePort
  ports:
    - name: '3001'
      port: 3001
      targetPort: 3001
  selector:
    app: uptimekuma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uptimekuma
  name: uptimekuma-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uptimekuma
  name: uptimekuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      containers:
        - name: uptimekuma
          image: louislam/uptime-kuma:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: web-ui
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: web-ui
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: web-ui
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/data
              name: uptimekuma-data
      restartPolicy: Always
      volumes:
        - name: uptimekuma-data
          persistentVolumeClaim:
            claimName: uptimekuma-data
